name: Explore GitHub-hosted runners

on:
  workflow_dispatch:

jobs:
  explore-linux-runner:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Exploration
        run: |
          set -x
          ls -l
          df -h
          whoami
          cat /etc/os-release
          cat /proc/cpuinfo
          docker ps
          free -h
          sudo apt update -q
          sudo apt install --no-install-recommends -q -y backblaze-b2 duc-nox

      - name: Tree
        run: |
          tree -ifpugDs / > tree.txt
          
      - name: Duc
        run: duc index /

      - name: Upload to Backblaze B2
        env:
          OPENDRR_B2_KEY_ID: ${{ secrets.OPENDRR_B2_KEY_ID }}
          OPENDRR_B2_APPLICATION_KEY: ${{ secrets.OPENDRR_B2_APPLICATION_KEY }}
        run: |
          set -x
          backblaze-b2 version
          backblaze-b2 authorize-account "$OPENDRR_B2_KEY_ID" "$OPENDRR_B2_APPLICATION_KEY"
          backblaze-b2 upload-file OpenDRR .duc.db github-ubuntu-20.04.duc.db
          backblaze-b2 upload-file OpenDRR tree.txt github-ubuntu-20.04-tree.txt
          backblaze-b2 clear-account


  explore-macos-runner:
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Exploration
        run: |
          set -x
          ls -l
          df -h
          whoami
          vm_stat
          which brew || :

      - name: Download OpenQuake
        run: curl https://raw.githubusercontent.com/gem/oq-engine/master/install.py -O

      - name: Install OpenQuake
        run: |
          set -x
          python3 --version
          python3 install.py user

      - name: See OpenQuake installation
        run: |
          set -x
          pwd
          du -csh *
          du -csh ~/*

      - name: Run OpenQuake
        run: |
          source ~/openquake/bin/activate

