name: Explore GitHub-hosted runners

# References:
# https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs

on:
  workflow_dispatch:
    inputs:
      runTreeAndDuc:
        description: 'Run tree and duc?'
        required: true
        default: 'false'

jobs:
  explore-linux-runner:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Exploration
        run: |
          set -x
          pwd
          ls -l
          whoami
          cat /etc/os-release
          cat /proc/cpuinfo
          docker ps
          docker compose --help || echo "No \"docker compose\""
          docker-compose --help
          free -h
          sudo apt update -q
          df -h
          mkdir ~/emptydir
          sudo eatmydata rsync -a --delete ~/emptydir /usr/share/dotnet
          sudo eatmydata rsync -a --delete ~/emptydir /usr/share/swift
          df -h

      - name: Install backblaze-b2 and duc-nox conditionally
        if: ${{ github.event.inputs.runTreeAndDuc != 'false' }}
        run: sudo apt install --no-install-recommends -q -y backblaze-b2 duc-nox

      - name: Tree
        if: ${{ github.event.inputs.runTreeAndDuc != 'false' }}
        run: |
          tree -ifpugDs / > ~/tree.txt
          
      - name: Duc
        if: ${{ github.event.inputs.runTreeAndDuc != 'false' }}
        run: duc index /

      - name: Upload to Backblaze B2
        if: ${{ github.event.inputs.runTreeAndDuc != 'false' }}
        env:
          OPENDRR_B2_KEY_ID: ${{ secrets.OPENDRR_B2_KEY_ID }}
          OPENDRR_B2_APPLICATION_KEY: ${{ secrets.OPENDRR_B2_APPLICATION_KEY }}
        run: |
          set -x
          backblaze-b2 version
          backblaze-b2 authorize-account "$OPENDRR_B2_KEY_ID" "$OPENDRR_B2_APPLICATION_KEY"
          backblaze-b2 upload-file OpenDRR ~/.duc.db github-ubuntu-20.04.duc.db
          backblaze-b2 upload-file OpenDRR ~/tree.txt github-ubuntu-20.04-tree.txt
          backblaze-b2 clear-account
