name: Explore gh

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      releaseTagForUploadingAssets:
        description: 'Existing release tag for uploading assets'
        required: false

jobs:
  gh-repo-list:
    runs-on: ubuntu-latest
    steps:
      - name: List all OpenDRR (public) repos
        run: gh repo list OpenDRR -L 200
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Calculate Git LFS data (storage) usage for each repo, see https://github.com/OpenDRR/opendrr/issues/133
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_PAT }}
        run: |
          repos=($(gh repo list OpenDRR -L 200 | cut -f1))
          for i in "${repos[@]}"; do
            GIT_LFS_SKIP_SMUDGE=1 time gh repo clone "$i"
            pushd "${i##*/}"  # See https://unix.stackexchange.com/questions/253524/dirname-and-basename-vs-parameter-expansion
            git lfs ls-files --debug | grep size: | grep -o '[0-9]\+' | paste -sd + - | bc | numfmt --to=iec --round=nearest --format="%.3f"
            git lfs ls-files --debug --all | grep size: | grep -o '[0-9]\+' | paste -sd + - | bc | numfmt --to=iec --round=nearest --format="%.3f"
            popd
          done
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
